const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });
const bcrypt = require('bcryptjs');
const { sequelize, User, BenfordAnalysis, TransactionAnomaly, EmbezzlementPattern, FraudScore, AuditLog, InvestigationReport } = require('./models');

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Database connected');
    await sequelize.sync({ force: true });
    console.log('Tables created');

    // Seed Users
    const hashedPassword = await bcrypt.hash('password123', 10);
    await User.bulkCreate([
      { email: 'admin@forensic.com', password: hashedPassword, name: 'Admin User', role: 'admin' },
      { email: 'analyst@forensic.com', password: hashedPassword, name: 'Jane Analyst', role: 'analyst' }
    ]);
    console.log('Users seeded');

    // Seed Benford Analyses (15 items)
    const benfordData = [
      { company_name: 'Acme Corp', dataset_type: 'Accounts Payable', total_transactions: 12500, deviation_score: 0.23, conformity_level: 'Non-conforming', risk_level: 'high', digit_distribution: {"1":0.25,"2":0.19,"3":0.14,"4":0.11,"5":0.09,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Significant deviation in leading digit 1 frequency' },
      { company_name: 'GlobalTech Industries', dataset_type: 'Revenue Entries', total_transactions: 8900, deviation_score: 0.05, conformity_level: 'Conforming', risk_level: 'low', digit_distribution: {"1":0.29,"2":0.18,"3":0.13,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Distribution closely matches expected Benford curve' },
      { company_name: 'Meridian Holdings', dataset_type: 'Expense Reports', total_transactions: 4200, deviation_score: 0.45, conformity_level: 'Non-conforming', risk_level: 'critical', digit_distribution: {"1":0.15,"2":0.22,"3":0.18,"4":0.12,"5":0.10,"6":0.08,"7":0.07,"8":0.05,"9":0.03}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Severe underrepresentation of digit 1, possible fabrication' },
      { company_name: 'Summit Financial Group', dataset_type: 'Journal Entries', total_transactions: 15600, deviation_score: 0.12, conformity_level: 'Marginally conforming', risk_level: 'medium', digit_distribution: {"1":0.27,"2":0.19,"3":0.13,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.05}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Slight deviation requires further investigation' },
      { company_name: 'Pacific Ventures LLC', dataset_type: 'Vendor Payments', total_transactions: 6700, deviation_score: 0.38, conformity_level: 'Non-conforming', risk_level: 'high', digit_distribution: {"1":0.20,"2":0.20,"3":0.15,"4":0.12,"5":0.10,"6":0.08,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Unusually flat distribution suggests round-number fabrication' },
      { company_name: 'Northern Star Corp', dataset_type: 'Sales Transactions', total_transactions: 22300, deviation_score: 0.03, conformity_level: 'Conforming', risk_level: 'low', digit_distribution: {"1":0.30,"2":0.18,"3":0.12,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Excellent conformity to Benford distribution' },
      { company_name: 'Cascade Manufacturing', dataset_type: 'Inventory Adjustments', total_transactions: 3100, deviation_score: 0.52, conformity_level: 'Non-conforming', risk_level: 'critical', digit_distribution: {"1":0.12,"2":0.15,"3":0.20,"4":0.15,"5":0.12,"6":0.09,"7":0.07,"8":0.06,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Extreme deviation, digit 3 anomalously high' },
      { company_name: 'Eastside Holdings', dataset_type: 'Cash Disbursements', total_transactions: 9400, deviation_score: 0.08, conformity_level: 'Conforming', risk_level: 'low', digit_distribution: {"1":0.29,"2":0.17,"3":0.13,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.05}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Within acceptable range' },
      { company_name: 'Bluewater Enterprises', dataset_type: 'Accounts Receivable', total_transactions: 5600, deviation_score: 0.31, conformity_level: 'Non-conforming', risk_level: 'high', digit_distribution: {"1":0.22,"2":0.21,"3":0.14,"4":0.11,"5":0.09,"6":0.08,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Digit 2 overrepresented, possible duplicate entries' },
      { company_name: 'Titan Logistics', dataset_type: 'Freight Invoices', total_transactions: 18200, deviation_score: 0.06, conformity_level: 'Conforming', risk_level: 'low', digit_distribution: {"1":0.30,"2":0.17,"3":0.13,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Normal distribution pattern' },
      { company_name: 'Phoenix Healthcare', dataset_type: 'Insurance Claims', total_transactions: 7800, deviation_score: 0.41, conformity_level: 'Non-conforming', risk_level: 'critical', digit_distribution: {"1":0.18,"2":0.16,"3":0.16,"4":0.13,"5":0.11,"6":0.09,"7":0.07,"8":0.06,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Suspicious uniform distribution in claims data' },
      { company_name: 'Sterling Associates', dataset_type: 'Consulting Fees', total_transactions: 2400, deviation_score: 0.29, conformity_level: 'Non-conforming', risk_level: 'high', digit_distribution: {"1":0.24,"2":0.20,"3":0.14,"4":0.11,"5":0.09,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Possible fee manipulation detected' },
      { company_name: 'Redwood Capital', dataset_type: 'Wire Transfers', total_transactions: 11300, deviation_score: 0.15, conformity_level: 'Marginally conforming', risk_level: 'medium', digit_distribution: {"1":0.26,"2":0.19,"3":0.13,"4":0.10,"5":0.09,"6":0.07,"7":0.06,"8":0.05,"9":0.05}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Borderline case, recommend quarterly monitoring' },
      { company_name: 'Coastal Development Co', dataset_type: 'Construction Invoices', total_transactions: 4800, deviation_score: 0.35, conformity_level: 'Non-conforming', risk_level: 'high', digit_distribution: {"1":0.21,"2":0.20,"3":0.15,"4":0.12,"5":0.10,"6":0.08,"7":0.06,"8":0.05,"9":0.03}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Inflated invoicing pattern suspected' },
      { company_name: 'Apex Trading Group', dataset_type: 'Trading Transactions', total_transactions: 31500, deviation_score: 0.04, conformity_level: 'Conforming', risk_level: 'low', digit_distribution: {"1":0.30,"2":0.18,"3":0.12,"4":0.10,"5":0.08,"6":0.07,"7":0.06,"8":0.05,"9":0.04}, expected_distribution: {"1":0.301,"2":0.176,"3":0.125,"4":0.097,"5":0.079,"6":0.067,"7":0.058,"8":0.051,"9":0.046}, notes: 'Large dataset with strong conformity' }
    ];
    await BenfordAnalysis.bulkCreate(benfordData);
    console.log('Benford analyses seeded (15 items)');

    // Seed Transaction Anomalies (15 items)
    const anomalyData = [
      { transaction_id: 'TXN-2024-001', account_name: 'Operating Account', amount: 999999.99, transaction_date: '2024-01-15', category: 'Wire Transfer', counterparty: 'Unknown Offshore LLC', anomaly_type: 'Structuring', anomaly_score: 0.95, description: 'Transaction just below $1M reporting threshold', status: 'flagged', risk_level: 'critical' },
      { transaction_id: 'TXN-2024-002', account_name: 'Payroll Account', amount: 45000.00, transaction_date: '2024-01-20', category: 'Payroll', counterparty: 'Ghost Employee Services', anomaly_type: 'Ghost Employee', anomaly_score: 0.88, description: 'Payment to non-existent employee, no matching HR records', status: 'under_review', risk_level: 'high' },
      { transaction_id: 'TXN-2024-003', account_name: 'Vendor Payments', amount: 125000.00, transaction_date: '2024-02-03', category: 'Vendor Payment', counterparty: 'Shell Corp International', anomaly_type: 'Shell Company', anomaly_score: 0.92, description: 'Payment to company with no physical address or employees', status: 'flagged', risk_level: 'critical' },
      { transaction_id: 'TXN-2024-004', account_name: 'Expense Account', amount: 9999.00, transaction_date: '2024-02-14', category: 'Expense Reimbursement', counterparty: 'John Smith', anomaly_type: 'Threshold Avoidance', anomaly_score: 0.76, description: 'Multiple expenses just below $10K approval threshold', status: 'flagged', risk_level: 'high' },
      { transaction_id: 'TXN-2024-005', account_name: 'Cash Account', amount: 8500.00, transaction_date: '2024-02-28', category: 'Cash Withdrawal', counterparty: 'ATM Network', anomaly_type: 'Velocity Anomaly', anomaly_score: 0.82, description: 'Rapid succession of large cash withdrawals over 3 days', status: 'under_review', risk_level: 'high' },
      { transaction_id: 'TXN-2024-006', account_name: 'Investment Account', amount: 2500000.00, transaction_date: '2024-03-05', category: 'Investment', counterparty: 'Cayman Islands Fund', anomaly_type: 'Layering', anomaly_score: 0.90, description: 'Funds routed through multiple jurisdictions before investment', status: 'flagged', risk_level: 'critical' },
      { transaction_id: 'TXN-2024-007', account_name: 'Accounts Payable', amount: 67500.00, transaction_date: '2024-03-12', category: 'Invoice Payment', counterparty: 'Duplicate Vendor Inc', anomaly_type: 'Duplicate Payment', anomaly_score: 0.85, description: 'Same invoice paid twice to different bank accounts', status: 'confirmed', risk_level: 'high' },
      { transaction_id: 'TXN-2024-008', account_name: 'Revenue Account', amount: 350000.00, transaction_date: '2024-03-20', category: 'Revenue', counterparty: 'Fictitious Client Corp', anomaly_type: 'Revenue Fabrication', anomaly_score: 0.93, description: 'Revenue entry with no corresponding contract or delivery', status: 'flagged', risk_level: 'critical' },
      { transaction_id: 'TXN-2024-009', account_name: 'Petty Cash', amount: 4999.50, transaction_date: '2024-04-01', category: 'Petty Cash', counterparty: 'Internal', anomaly_type: 'Round-trip', anomaly_score: 0.71, description: 'Cash withdrawn and redeposited through different account', status: 'under_review', risk_level: 'medium' },
      { transaction_id: 'TXN-2024-010', account_name: 'Construction Fund', amount: 890000.00, transaction_date: '2024-04-15', category: 'Contract Payment', counterparty: 'Related Party Construction', anomaly_type: 'Related Party', anomaly_score: 0.87, description: 'Inflated contract with CFOs brother-in-law company', status: 'flagged', risk_level: 'high' },
      { transaction_id: 'TXN-2024-011', account_name: 'Marketing Budget', amount: 175000.00, transaction_date: '2024-04-22', category: 'Marketing', counterparty: 'Phantom Marketing Agency', anomaly_type: 'Fictitious Vendor', anomaly_score: 0.89, description: 'Marketing agency has no online presence or portfolio', status: 'flagged', risk_level: 'high' },
      { transaction_id: 'TXN-2024-012', account_name: 'Travel Expenses', amount: 28500.00, transaction_date: '2024-05-03', category: 'Travel', counterparty: 'Luxury Travel Co', anomaly_type: 'Expense Inflation', anomaly_score: 0.74, description: 'Travel expenses 3x average for similar trips', status: 'under_review', risk_level: 'medium' },
      { transaction_id: 'TXN-2024-013', account_name: 'Equipment Fund', amount: 445000.00, transaction_date: '2024-05-18', category: 'Equipment Purchase', counterparty: 'Overpriced Equipment LLC', anomaly_type: 'Price Manipulation', anomaly_score: 0.86, description: 'Equipment purchased at 200% market value', status: 'flagged', risk_level: 'high' },
      { transaction_id: 'TXN-2024-014', account_name: 'Consulting Fees', amount: 95000.00, transaction_date: '2024-06-01', category: 'Consulting', counterparty: 'Executive Spouse LLC', anomaly_type: 'Conflict of Interest', anomaly_score: 0.91, description: 'Consulting fee paid to entity owned by board member spouse', status: 'flagged', risk_level: 'critical' },
      { transaction_id: 'TXN-2024-015', account_name: 'Charity Fund', amount: 500000.00, transaction_date: '2024-06-15', category: 'Donation', counterparty: 'Fake Charity Foundation', anomaly_type: 'Charitable Fraud', anomaly_score: 0.83, description: 'Large donation to unregistered charity with kickback suspicion', status: 'under_review', risk_level: 'high' }
    ];
    await TransactionAnomaly.bulkCreate(anomalyData);
    console.log('Transaction anomalies seeded (15 items)');

    // Seed Embezzlement Patterns (15 items)
    const embezzlementData = [
      { case_id: 'EMB-2024-001', suspect_name: 'Robert Chen', department: 'Finance', pattern_type: 'Skimming', estimated_loss: 450000.00, detection_date: '2024-01-20', period_start: '2022-06-01', period_end: '2024-01-15', evidence_count: 23, confidence_score: 0.92, status: 'confirmed', risk_level: 'critical', description: 'Systematic skimming of cash receipts before recording in books' },
      { case_id: 'EMB-2024-002', suspect_name: 'Sarah Mitchell', department: 'Accounts Payable', pattern_type: 'Billing Scheme', estimated_loss: 780000.00, detection_date: '2024-02-10', period_start: '2021-03-01', period_end: '2024-02-01', evidence_count: 45, confidence_score: 0.95, status: 'confirmed', risk_level: 'critical', description: 'Created fictitious vendors and approved payments to personal accounts' },
      { case_id: 'EMB-2024-003', suspect_name: 'David Park', department: 'HR', pattern_type: 'Ghost Employee', estimated_loss: 320000.00, detection_date: '2024-03-05', period_start: '2022-01-01', period_end: '2024-02-28', evidence_count: 18, confidence_score: 0.88, status: 'under_investigation', risk_level: 'high', description: 'Added non-existent employees to payroll and diverted salaries' },
      { case_id: 'EMB-2024-004', suspect_name: 'Jennifer Walsh', department: 'Procurement', pattern_type: 'Kickback Scheme', estimated_loss: 1200000.00, detection_date: '2024-03-20', period_start: '2020-06-01', period_end: '2024-03-15', evidence_count: 67, confidence_score: 0.94, status: 'confirmed', risk_level: 'critical', description: 'Received kickbacks from vendors in exchange for inflated contracts' },
      { case_id: 'EMB-2024-005', suspect_name: 'Michael Torres', department: 'Treasury', pattern_type: 'Check Tampering', estimated_loss: 195000.00, detection_date: '2024-04-01', period_start: '2023-01-01', period_end: '2024-03-30', evidence_count: 12, confidence_score: 0.81, status: 'under_investigation', risk_level: 'high', description: 'Altered check amounts and forged signatures on company checks' },
      { case_id: 'EMB-2024-006', suspect_name: 'Lisa Crawford', department: 'Sales', pattern_type: 'Revenue Diversion', estimated_loss: 560000.00, detection_date: '2024-04-15', period_start: '2022-09-01', period_end: '2024-04-10', evidence_count: 34, confidence_score: 0.89, status: 'confirmed', risk_level: 'critical', description: 'Diverted customer payments to personal account through lapping scheme' },
      { case_id: 'EMB-2024-007', suspect_name: 'James Anderson', department: 'IT', pattern_type: 'Data Manipulation', estimated_loss: 890000.00, detection_date: '2024-05-02', period_start: '2021-01-01', period_end: '2024-04-30', evidence_count: 56, confidence_score: 0.93, status: 'confirmed', risk_level: 'critical', description: 'Manipulated financial database records to conceal unauthorized transfers' },
      { case_id: 'EMB-2024-008', suspect_name: 'Karen Phillips', department: 'Expense Management', pattern_type: 'Expense Padding', estimated_loss: 145000.00, detection_date: '2024-05-18', period_start: '2023-06-01', period_end: '2024-05-15', evidence_count: 28, confidence_score: 0.79, status: 'under_investigation', risk_level: 'medium', description: 'Systematically inflated expense reports with fictitious receipts' },
      { case_id: 'EMB-2024-009', suspect_name: 'Thomas Wright', department: 'Operations', pattern_type: 'Asset Misappropriation', estimated_loss: 670000.00, detection_date: '2024-06-03', period_start: '2022-03-01', period_end: '2024-05-30', evidence_count: 41, confidence_score: 0.91, status: 'confirmed', risk_level: 'critical', description: 'Diverted company equipment and inventory for personal resale' },
      { case_id: 'EMB-2024-010', suspect_name: 'Amanda Foster', department: 'Accounting', pattern_type: 'Journal Entry Fraud', estimated_loss: 2100000.00, detection_date: '2024-06-20', period_start: '2020-01-01', period_end: '2024-06-15', evidence_count: 89, confidence_score: 0.97, status: 'confirmed', risk_level: 'critical', description: 'Fabricated journal entries to cover unauthorized fund transfers' },
      { case_id: 'EMB-2024-011', suspect_name: 'Brian Cooper', department: 'Purchasing', pattern_type: 'Purchase Order Fraud', estimated_loss: 430000.00, detection_date: '2024-07-05', period_start: '2023-01-01', period_end: '2024-06-30', evidence_count: 25, confidence_score: 0.84, status: 'under_investigation', risk_level: 'high', description: 'Created fraudulent purchase orders for non-existent goods' },
      { case_id: 'EMB-2024-012', suspect_name: 'Nicole Davis', department: 'Payroll', pattern_type: 'Payroll Manipulation', estimated_loss: 275000.00, detection_date: '2024-07-22', period_start: '2022-07-01', period_end: '2024-07-20', evidence_count: 19, confidence_score: 0.86, status: 'under_investigation', risk_level: 'high', description: 'Altered overtime records and added unauthorized bonuses' },
      { case_id: 'EMB-2024-013', suspect_name: 'Richard Lee', department: 'Legal', pattern_type: 'Wire Transfer Fraud', estimated_loss: 1500000.00, detection_date: '2024-08-01', period_start: '2021-06-01', period_end: '2024-07-30', evidence_count: 52, confidence_score: 0.96, status: 'confirmed', risk_level: 'critical', description: 'Initiated unauthorized wire transfers to offshore accounts using forged approvals' },
      { case_id: 'EMB-2024-014', suspect_name: 'Patricia Martinez', department: 'Customer Service', pattern_type: 'Refund Fraud', estimated_loss: 185000.00, detection_date: '2024-08-15', period_start: '2023-03-01', period_end: '2024-08-10', evidence_count: 31, confidence_score: 0.82, status: 'under_investigation', risk_level: 'medium', description: 'Issued fictitious refunds to personal credit cards' },
      { case_id: 'EMB-2024-015', suspect_name: 'Steven Brown', department: 'Executive', pattern_type: 'Executive Override', estimated_loss: 3500000.00, detection_date: '2024-09-01', period_start: '2019-01-01', period_end: '2024-08-30', evidence_count: 112, confidence_score: 0.98, status: 'confirmed', risk_level: 'critical', description: 'CEO systematically overrode controls to authorize personal expenditures as business expenses' }
    ];
    await EmbezzlementPattern.bulkCreate(embezzlementData);
    console.log('Embezzlement patterns seeded (15 items)');

    // Seed Fraud Scores (15 items)
    const fraudData = [
      { company_name: 'Enron Legacy Corp', fiscal_year: 'FY2023', overall_score: 0.92, revenue_manipulation_score: 0.95, expense_manipulation_score: 0.88, asset_misstatement_score: 0.91, disclosure_score: 0.85, altman_z_score: 0.8, beneish_m_score: -1.5, risk_level: 'critical', red_flags: ['Revenue recognition manipulation','Off-balance sheet entities','Related party transactions','Unusual revenue growth'], notes: 'Multiple red flags across all categories' },
      { company_name: 'Worldcom Ventures', fiscal_year: 'FY2023', overall_score: 0.88, revenue_manipulation_score: 0.82, expense_manipulation_score: 0.94, asset_misstatement_score: 0.86, disclosure_score: 0.79, altman_z_score: 1.2, beneish_m_score: -2.0, risk_level: 'critical', red_flags: ['Capitalized operating expenses','Inflated assets','Cookie jar reserves','Aggressive depreciation'], notes: 'Expense manipulation is primary concern' },
      { company_name: 'Clean Energy Solutions', fiscal_year: 'FY2023', overall_score: 0.15, revenue_manipulation_score: 0.12, expense_manipulation_score: 0.18, asset_misstatement_score: 0.14, disclosure_score: 0.10, altman_z_score: 3.5, beneish_m_score: -3.2, risk_level: 'low', red_flags: [], notes: 'Low risk across all metrics' },
      { company_name: 'TechStart Innovations', fiscal_year: 'FY2023', overall_score: 0.45, revenue_manipulation_score: 0.52, expense_manipulation_score: 0.38, asset_misstatement_score: 0.42, disclosure_score: 0.35, altman_z_score: 2.4, beneish_m_score: -2.5, risk_level: 'medium', red_flags: ['Aggressive revenue recognition','Channel stuffing indicators'], notes: 'Revenue timing concerns noted' },
      { company_name: 'Global Pharma Inc', fiscal_year: 'FY2023', overall_score: 0.72, revenue_manipulation_score: 0.68, expense_manipulation_score: 0.75, asset_misstatement_score: 0.78, disclosure_score: 0.65, altman_z_score: 1.8, beneish_m_score: -1.8, risk_level: 'high', red_flags: ['Inventory valuation issues','R&D cost capitalization','Related party sales','Unusual accruals'], notes: 'Multiple areas of concern in financial statements' },
      { company_name: 'AutoDrive Systems', fiscal_year: 'FY2023', overall_score: 0.31, revenue_manipulation_score: 0.28, expense_manipulation_score: 0.34, asset_misstatement_score: 0.30, disclosure_score: 0.25, altman_z_score: 2.9, beneish_m_score: -2.9, risk_level: 'low', red_flags: ['Minor timing differences'], notes: 'Generally clean with minor observations' },
      { company_name: 'Oceanic Shipping Ltd', fiscal_year: 'FY2023', overall_score: 0.67, revenue_manipulation_score: 0.71, expense_manipulation_score: 0.63, asset_misstatement_score: 0.69, disclosure_score: 0.58, altman_z_score: 1.6, beneish_m_score: -2.1, risk_level: 'high', red_flags: ['Bill and hold transactions','Percentage completion manipulation','Asset impairment delays'], notes: 'Revenue recognition and asset valuation concerns' },
      { company_name: 'Metro Construction Group', fiscal_year: 'FY2023', overall_score: 0.81, revenue_manipulation_score: 0.85, expense_manipulation_score: 0.78, asset_misstatement_score: 0.83, disclosure_score: 0.72, altman_z_score: 1.1, beneish_m_score: -1.6, risk_level: 'critical', red_flags: ['Cost overrun concealment','Change order manipulation','Progress billing fraud','Fictitious subcontractors'], notes: 'Construction industry specific fraud indicators present' },
      { company_name: 'Digital Media Corp', fiscal_year: 'FY2023', overall_score: 0.22, revenue_manipulation_score: 0.20, expense_manipulation_score: 0.25, asset_misstatement_score: 0.19, disclosure_score: 0.18, altman_z_score: 3.2, beneish_m_score: -3.0, risk_level: 'low', red_flags: [], notes: 'Clean financials with strong controls' },
      { company_name: 'Sunrise Banking Corp', fiscal_year: 'FY2023', overall_score: 0.58, revenue_manipulation_score: 0.55, expense_manipulation_score: 0.61, asset_misstatement_score: 0.56, disclosure_score: 0.52, altman_z_score: 2.0, beneish_m_score: -2.3, risk_level: 'medium', red_flags: ['Loan loss provision manipulation','Interest income timing','Off-balance sheet exposure'], notes: 'Banking sector specific concerns noted' },
      { company_name: 'Falcon Airlines', fiscal_year: 'FY2023', overall_score: 0.76, revenue_manipulation_score: 0.73, expense_manipulation_score: 0.79, asset_misstatement_score: 0.74, disclosure_score: 0.68, altman_z_score: 1.4, beneish_m_score: -1.9, risk_level: 'high', red_flags: ['Maintenance reserve manipulation','Fuel hedging irregularities','Lease classification issues','Loyalty program liability understatement'], notes: 'Multiple industry-specific red flags' },
      { company_name: 'Heritage Real Estate', fiscal_year: 'FY2023', overall_score: 0.84, revenue_manipulation_score: 0.87, expense_manipulation_score: 0.81, asset_misstatement_score: 0.89, disclosure_score: 0.74, altman_z_score: 1.0, beneish_m_score: -1.4, risk_level: 'critical', red_flags: ['Property valuation inflation','Rental income fabrication','Related party transactions','Undisclosed liabilities'], notes: 'Severe asset overstatement suspected' },
      { company_name: 'NovaTech Solutions', fiscal_year: 'FY2023', overall_score: 0.38, revenue_manipulation_score: 0.42, expense_manipulation_score: 0.35, asset_misstatement_score: 0.36, disclosure_score: 0.32, altman_z_score: 2.7, beneish_m_score: -2.7, risk_level: 'medium', red_flags: ['Software revenue recognition timing'], notes: 'Minor revenue timing concern, otherwise clean' },
      { company_name: 'Continental Mining', fiscal_year: 'FY2023', overall_score: 0.69, revenue_manipulation_score: 0.65, expense_manipulation_score: 0.72, asset_misstatement_score: 0.71, disclosure_score: 0.62, altman_z_score: 1.7, beneish_m_score: -2.0, risk_level: 'high', red_flags: ['Reserve estimation manipulation','Environmental liability understatement','Asset impairment avoidance'], notes: 'Mining industry specific fraud indicators' },
      { company_name: 'Premier Retail Holdings', fiscal_year: 'FY2023', overall_score: 0.53, revenue_manipulation_score: 0.56, expense_manipulation_score: 0.50, asset_misstatement_score: 0.52, disclosure_score: 0.48, altman_z_score: 2.2, beneish_m_score: -2.4, risk_level: 'medium', red_flags: ['Inventory shrinkage concealment','Same-store sales inflation'], notes: 'Retail sector concerns, moderate risk' }
    ];
    await FraudScore.bulkCreate(fraudData);
    console.log('Fraud scores seeded (15 items)');

    // Seed Audit Logs (10 items)
    const auditData = [
      { user_id: 1, user_name: 'Admin User', action: 'login', entity_type: null, entity_id: null, details: { method: 'password' }, ip_address: '192.168.1.10' },
      { user_id: 2, user_name: 'Jane Analyst', action: 'create', entity_type: 'benford_analysis', entity_id: 1, details: { company_name: 'Acme Corp' }, ip_address: '192.168.1.25' },
      { user_id: 2, user_name: 'Jane Analyst', action: 'update', entity_type: 'transaction_anomaly', entity_id: 3, details: { field: 'status', old_value: 'flagged', new_value: 'under_review' }, ip_address: '192.168.1.25' },
      { user_id: 1, user_name: 'Admin User', action: 'export', entity_type: 'benford_analysis', entity_id: null, details: { format: 'csv', record_count: 15 }, ip_address: '192.168.1.10' },
      { user_id: 2, user_name: 'Jane Analyst', action: 'create', entity_type: 'embezzlement_pattern', entity_id: 5, details: { case_id: 'EMB-2024-005' }, ip_address: '192.168.1.25' },
      { user_id: 1, user_name: 'Admin User', action: 'delete', entity_type: 'fraud_score', entity_id: 8, details: { reason: 'duplicate entry' }, ip_address: '192.168.1.10' },
      { user_id: 2, user_name: 'Jane Analyst', action: 'import', entity_type: 'transaction_anomaly', entity_id: null, details: { record_count: 25, source: 'bank_export.csv' }, ip_address: '192.168.1.25' },
      { user_id: 1, user_name: 'Admin User', action: 'update', entity_type: 'embezzlement_pattern', entity_id: 2, details: { field: 'status', old_value: 'under_investigation', new_value: 'confirmed' }, ip_address: '192.168.1.10' },
      { user_id: 2, user_name: 'Jane Analyst', action: 'login', entity_type: null, entity_id: null, details: { method: 'password' }, ip_address: '10.0.0.45' },
      { user_id: 1, user_name: 'Admin User', action: 'create', entity_type: 'investigation_report', entity_id: 1, details: { report_number: 'RPT-2024-001' }, ip_address: '192.168.1.10' }
    ];
    await AuditLog.bulkCreate(auditData);
    console.log('Audit logs seeded (10 items)');

    // Seed Investigation Reports (8 items)
    const reportData = [
      { report_number: 'RPT-2024-001', title: 'Acme Corp Accounts Payable Investigation', investigator_name: 'Jane Analyst', status: 'final', priority: 'high', summary: 'Investigation into anomalous accounts payable transactions at Acme Corp.', findings: 'Multiple fictitious vendor payments identified totaling $780,000. Evidence of billing scheme operated by AP manager.', recommendations: 'Terminate implicated employee. Implement dual-approval for vendor creation. Conduct full forensic audit of AP records for past 3 years.', related_cases: ['EMB-2024-002'], evidence_summary: { documents: 45, interviews: 8, bank_records: 12 }, period_start: '2021-03-01', period_end: '2024-02-01', total_amount_at_risk: 780000.00 },
      { report_number: 'RPT-2024-002', title: 'Meridian Holdings Expense Report Fraud', investigator_name: 'Admin User', status: 'final', priority: 'critical', summary: 'Investigation of systematic expense report manipulation at Meridian Holdings.', findings: 'Expense reports fabricated with fictitious receipts. Deviation score of 0.45 confirmed data manipulation.', recommendations: 'Implement automated receipt verification. Require manager sign-off for all expenses above $500.', related_cases: ['EMB-2024-008'], evidence_summary: { documents: 28, interviews: 5, digital_forensics: 3 }, period_start: '2023-06-01', period_end: '2024-05-15', total_amount_at_risk: 145000.00 },
      { report_number: 'RPT-2024-003', title: 'Pacific Ventures Vendor Payment Analysis', investigator_name: 'Jane Analyst', status: 'in_progress', priority: 'high', summary: 'Analysis of suspicious vendor payment patterns at Pacific Ventures LLC.', findings: 'Flat digit distribution in vendor payments suggests round-number fabrication. Several vendors lack verifiable business presence.', recommendations: 'Pending completion of investigation.', related_cases: [], evidence_summary: { documents: 34, vendor_verifications: 15 }, period_start: '2022-01-01', period_end: '2024-06-30', total_amount_at_risk: 560000.00 },
      { report_number: 'RPT-2024-004', title: 'Phoenix Healthcare Insurance Claims Review', investigator_name: 'Admin User', status: 'review', priority: 'critical', summary: 'Review of suspicious insurance claims patterns at Phoenix Healthcare.', findings: 'Uniform distribution in claims data highly indicative of fabricated claims. Estimated 30% of claims may be fraudulent.', recommendations: 'Engage external auditors. Report findings to insurance regulators. Implement AI-based claims screening.', related_cases: [], evidence_summary: { claims_reviewed: 7800, suspicious_claims: 2340, interviews: 12 }, period_start: '2023-01-01', period_end: '2024-06-01', total_amount_at_risk: 3200000.00 },
      { report_number: 'RPT-2024-005', title: 'Cascade Manufacturing Inventory Discrepancy', investigator_name: 'Jane Analyst', status: 'in_progress', priority: 'high', summary: 'Investigation into extreme Benford deviation in inventory adjustment records.', findings: 'Digit 3 anomalously high in inventory adjustments. Physical counts do not match recorded inventory levels.', recommendations: 'Pending further analysis.', related_cases: ['EMB-2024-009'], evidence_summary: { documents: 41, physical_counts: 6 }, period_start: '2022-03-01', period_end: '2024-05-30', total_amount_at_risk: 670000.00 },
      { report_number: 'RPT-2024-006', title: 'Offshore Wire Transfer Investigation', investigator_name: 'Admin User', status: 'draft', priority: 'critical', summary: 'Investigation of large wire transfers routed through offshore jurisdictions.', findings: 'Preliminary analysis shows layering pattern consistent with money laundering.', recommendations: 'Draft stage - recommendations pending.', related_cases: ['EMB-2024-013'], evidence_summary: { wire_transfers: 52, jurisdictions: 7 }, period_start: '2021-06-01', period_end: '2024-07-30', total_amount_at_risk: 2500000.00 },
      { report_number: 'RPT-2024-007', title: 'Executive Override Controls Assessment', investigator_name: 'Jane Analyst', status: 'final', priority: 'critical', summary: 'Assessment of CEO override of internal controls for personal expenditures.', findings: 'CEO systematically bypassed approval controls over 5-year period. Total unauthorized expenditures exceed $3.5M.', recommendations: 'Board intervention required. Engage legal counsel. Implement controls that cannot be overridden by any single individual.', related_cases: ['EMB-2024-015'], evidence_summary: { documents: 112, override_instances: 89, interviews: 15 }, period_start: '2019-01-01', period_end: '2024-08-30', total_amount_at_risk: 3500000.00 },
      { report_number: 'RPT-2024-008', title: 'Related Party Construction Contract Review', investigator_name: 'Admin User', status: 'review', priority: 'medium', summary: 'Review of construction contract awarded to company owned by CFO relative.', findings: 'Contract pricing 40% above market rates. No competitive bidding process followed.', recommendations: 'Void current contract. Implement mandatory competitive bidding for all contracts above $100K. Review conflict of interest policies.', related_cases: [], evidence_summary: { contracts: 3, market_comparisons: 8, interviews: 4 }, period_start: '2023-06-01', period_end: '2024-04-15', total_amount_at_risk: 890000.00 }
    ];
    await InvestigationReport.bulkCreate(reportData);
    console.log('Investigation reports seeded (8 items)');

    console.log('\n=== Seeding completed successfully ===');
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

seed();
